### ISSUE TITLE
Unsure how to use the template

### ISSUE THREAD

**Issue by patrick-han** [nasosi/C4EngineExamples#2]
Hi! Thank you for putting this together.

I've managed to build and run the Engine as-is in the form it's cloned, and I've been trying to get this repo to build/work as well.

After building the solution, which project should be set as the Startup Project? I assume C4Engine, but I seem to be getting a runtime error when I try to launch it, even though the engine.exe I originally built runs fine on its own:

![image](https://github.com/nasosi/C4EngineExamples/assets/47380073/ff834858-bdef-41a0-9fb6-d0ff68bcccc9)

Additionally, which files should I include when I create my own project? I assume the root CMakeLists as well as the cmake folder. I'm not too terribly well-versed in cmake so I was unsure.

**Comment by nasosi** [comment]
Yes it should be set to C4Engine.

Which msvc version are you using?

Also have you set the C4ActiveApp cmake variable and reconfigured cmake after doing so?

In addition check the binary output directories. Does the directory that contain the engine executable also contains the activeapp dll (for example 001_simple)?




Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Patrick Han ***@***.***>
Sent: Saturday, September 16, 2023 11:45:17 PM
To: nasosi/C4EngineExamples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nasosi/C4EngineExamples] Unsure how to use the template (Issue #2)


Hi! Thank you for putting this together.

I've managed to build and run the Engine as-is in the form it's cloned, and I've been trying to get this repo to build/work as well.

After building the solution, which project should be set as the Startup Project? I assume C4Engine, but I seem to be getting a runtime error when I try to launch it, even though the engine.exe I originally built runs fine on its own:

[image]<https://user-images.githubusercontent.com/47380073/268481483-ff834858-bdef-41a0-9fb6-d0ff68bcccc9.png>

**Comment by patrick-han** [comment]
I'm using VS2022 with compiler version 1934.
I've tried setting 001_simple as the C4ActiveApp with the same results.

Yes when I open C4EngineExamples\build\ProgramFiles\Debug I see all the .dll files along with C4Engine.exe

**Comment by nasosi** [comment]
Hello,

I can now reproduce the issue and will try to resolve this.

Thank you.

**Comment by nasosi** [comment]
> I'm using VS2022 with compiler version 1934. I've tried setting 001_simple as the C4ActiveApp with the same results.
> 
> Yes when I open C4EngineExamples\build\ProgramFiles\Debug I see all the .dll files along with C4Engine.exe

@patrick-han, did you clone the repository or you downloaded the .zip file?

**Comment by patrick-han** [comment]
> > I'm using VS2022 with compiler version 1934. I've tried setting 001_simple as the C4ActiveApp with the same results.
> 
> > 
> 
> > Yes when I open C4EngineExamples\build\ProgramFiles\Debug I see all the .dll files along with C4Engine.exe
> 
> 
> 
> @patrick-han, did you clone the repository or you downloaded the .zip file?
> 
> 

I cloned the repository.

**Comment by nasosi** [comment]
> > > I'm using VS2022 with compiler version 1934. I've tried setting 001_simple as the C4ActiveApp with the same results.
> > 
> > 
> > > 
> > 
> > 
> > > Yes when I open C4EngineExamples\build\ProgramFiles\Debug I see all the .dll files along with C4Engine.exe
> > 
> > 
> > @patrick-han, did you clone the repository or you downloaded the .zip file?
> 
> I cloned the repository.

I just changed  the github settings to fix an issue where lfs files were not included in the .zip archive and would result in crash at startup since the .wld files were essentially empty.  A cloned repository should have been working OK though and this shouldn't have affected you.

Can you please try to follow the steps as shown in the video below and let me know if it works or not? Because MSVC has some issues with cmake please make an attempt to reproduce the steps as close as possible.

Notes: 
1. The compile order may cause a failure. Perform a "build all" a couple of times if this occurs. This will be fixed in a subsequent version
2. During compilation cmake will attempt to start C4 to import resources. You should the click "import" once, and then type "~" followed by "quit" and Enter, to exit the engine. 



https://github.com/nasosi/C4EngineExamples/assets/2938701/5e10a96e-8b0d-4b87-b8d6-b7c41f72d789


Thank you!

**Comment by patrick-han** [comment]
> > > > I'm using VS2022 with compiler version 1934. I've tried setting 001_simple as the C4ActiveApp with the same results.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Yes when I open C4EngineExamples\build\ProgramFiles\Debug I see all the .dll files along with C4Engine.exe
> > > 
> > > 
> > > @patrick-han, did you clone the repository or you downloaded the .zip file?
> > 
> > 
> > I cloned the repository.
> 
> I just changed the github settings to fix an issue where lfs files were not included in the .zip archive and would result in crash at startup since the .wld files were essentially empty. A cloned repository should have been working OK though and this shouldn't have affected you.
> 
> Can you please try to follow the steps as shown in the video below and let me know if it works or not? Because MSVC has some issues with cmake please make an attempt to reproduce the steps as close as possible.
> 
> Notes:
> 
>     1. The compile order may cause a failure. Perform a "build all" a couple of times if this occurs. This will be fixed in a subsequent version
> 
>     2. During compilation, cmake will attempt to start C4 to import resources. You should then click "import" once, and then type "~" followed by "quit" and Enter, to exit the engine.
> 
> 
> Setup.mp4
> 
> Thank you!

Hey I just tried this following the exact steps and it's working now! I guess the process was a lot more involved than I thought.

A couple notes:

1. I originally had the data stuff extracted to the same folder as the engine, like Eric mentions in the getting started guide on the wiki: https://c4engine.com/wiki/index.php?title=Getting_Started (instead of having the data folder side by side with the C4 Engine repo). So I had both the code root and data root pointing to the C4-Engine folder. Not sure if this would have made a difference.

2. I was using the CMake gui program to do this originally. All I did was point the source code originally to the root folder of the examples repo and then I made a build folder for the "Where to build binaries" field. Then configure + generate. I guess maybe this is not sufficient? Since it seems in this video you manually created a build configuration.

**Comment by nasosi** [comment]
Great!

1. It should work even if you place them in the same folder.  
2. Correct. CMake GUI will generate an MSVC solution, but the examples are taking advantage of cmake itself for various configuration steps, like importing resources. I hope that C4Engine will change the way it imports resources in the future so this will not be necessary. In any case, because of these configuration steps, it is preferred to use the MSVC's cmake support and I don't think that this functionality would can work with a .sln.

Also to answer your original question, here is a video on how to create your own project by cloning 001_simple.


https://github.com/nasosi/C4EngineExamples/assets/2938701/5c15aadb-7746-4877-bacf-4a9b5dc2d738


I was planning to create these little videos for the folks that are not familiar with cmake. This was a good excuse to put them together..
